openapi: 3.0.0
info:
  version: 0.0.1
  title: Go Gin Framework Rest API
  description: Example go using gin framework implementation rest api
  contact:
    name: Louis Plancher
    url: https://github.com/lplanch
    email: pro@lplanch.com
servers:
  - url: 'http://{host}:4000/api/v1'
    description: go service api server endpoint application
    variables:
      host:
        default: localhost
        enum:
          - localhost
paths:
  ############################
  ## HEALTHCHECK ENDPOINT
  ############################
  /health:
    post:
      tags:
        - misc
      summary: Healthcheck endpoint
      description: Check the state of the API
      responses:
        '200':
          description: Healthcheck successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusCode:
                    type: integer
                    format: number
                    example: 200
                  Method:
                    type: string
                    example: GET
                  Message:
                    type: string
                  Data:
                    $ref: '#/components/schemas/Health'
                required:
                  - StatusCode
                  - Method
                  - Message
                  - Data
        '400':
          description: |
            Parsing json data failed,
            Generate accessToken failed,
            Sending email activation failed
        '403':
          description: Register new account failed"
        '409':
          description: Email already exist
  #################################
  #################################
  ## COMPONENTS AUTH TERITORY
  #################################
  #################################
components:
  schemas:
    Health:
      properties:
        Status:
          type: string
          example: "Available"
        Uptime:
          type: number
          example: 1294231
          description: API uptime in milliseconds
        Date:
          type: string
          example: "2024-02-16T10:37:42.452213+01:00"
          description: Current date
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
